apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: route-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-service
  template:
    metadata:
      labels:
        app: route-service
    spec:
      containers:
      - name: cloud-config
        image: vsenkiv/route-service:latest
        command: [ "java", "-jar", "/opt/route/route-service-0.0.1-SNAPSHOT.jar" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: route-service
spec:
  ports:
  - port: 8080
  selector:
    app: route-service